### PR TITLE
🍱 Adds Apache Druid

### PR DESCRIPTION
**Pull request by gidoUninova**
New icon for apache druid

### CODE REVIEW

**Comment by walkxcode** [comment]
Do you have a cropped version of the datahub icon (see screenshot) and a PNG version of it? 

image

**Comment by walkxcode** [comment]
@gidoUninova reminder

**Comment by gidoUninova** [comment]
Actually I have not. I can arrange a cropped version but not with transparent background. Is ti ok?

**Comment by gidoUninova** [comment]
I removed previous version of the data hub logo and added a new one cropped

**Comment by walkxcode** [comment]
Hey, sorry for the delayed response, I was on vacation.

I have merged your pr! Thank you for your contribution.

**Pull request merged**
