### PR TITLE
🍱 Add runonflux

### PR DESCRIPTION
**Pull request by matthewjdegarmo**

### CODE REVIEW

**Comment by walkxcode** [comment]
The quality of the image is too low, do you have any higher quality images?

**Comment by matthewjdegarmo** [comment]
I'll take a look. I thought it was better for some reason. I'll update this PR with a higher quality one.

**Comment by matthewjdegarmo** [comment]
@walkxcode I've added two icons (one being the replacement to the original)

Are these good enough?

**Comment by walkxcode** [comment]
Perfect!

**Pull request merged**
